/**
 * Prompt Configuration Service
 * Handles storage, retrieval, and variable substitution for AI prompts
 */

import { getSupabaseAdmin } from '@/lib/supabase-admin';

// ============================================================================
// Types and Interfaces
// ============================================================================

export interface PromptConfig {
  systemPrompt: string;
  userPrompt: string;
}

export interface PromptVariables {
  job_title: string;
  existing_topics: string;
  chosen_topics: string;
  generated_topics_history: string;
  count: number;
  style_samples: string;
}

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

// ============================================================================
// Constants
// ============================================================================

export const SUPPORTED_VARIABLES = [
  'job_title',
  'existing_topics',
  'chosen_topics',
  'generated_topics_history',
  'count',
  'style_samples',
] as const;

export type SupportedVariable = (typeof SUPPORTED_VARIABLES)[number];

// Database keys for app_config table
export const PROMPT_CONFIG_KEYS = {
  SYSTEM_PROMPT: 'ai_system_prompt',
  USER_PROMPT: 'ai_user_prompt',
} as const;

// Default prompts (used when no custom prompts exist)
export const DEFAULT_SYSTEM_PROMPT = `You're a LinkedIn topic drafter. Your job is to act as a {{job_title}}, look at the topic ideas already drafted and generate {{count}} more like it that are different enough to be novel.

Each topic should be:
- Specific and actionable
- Written as a compelling LinkedIn post title
- Different from the existing topics but in a similar professional domain
- Formatted like: "Why [Problem/Observation]—And [Solution/Insight]"

Return ONLY a JSON array of topic strings, nothing else.`;

export const DEFAULT_USER_PROMPT = `Here are the existing topic ideas:
{{existing_topics}}

Generate {{count}} new topic ideas that are different but related to these themes.

Return only a JSON array of {{count}} topic strings.`;

export const DEFAULT_PROMPT_CONFIG: PromptConfig = {
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  userPrompt: DEFAULT_USER_PROMPT,
};

// Sample data for preview functionality
export const SAMPLE_VARIABLES: PromptVariables = {
  job_title: 'Senior Product Manager',
  existing_topics:
    '- Why Most Product Roadmaps Fail—And How to Fix Yours\n- The Hidden Cost of Feature Creep—And What Smart PMs Do Instead',
  chosen_topics:
    '- Why Most Product Roadmaps Fail—And How to Fix Yours\n- The Hidden Cost of Feature Creep—And What Smart PMs Do Instead',
  generated_topics_history:
    '- Why Most Product Roadmaps Fail—And How to Fix Yours\n- The Hidden Cost of Feature Creep—And What Smart PMs Do Instead\n- How to Say No to Stakeholders Without Burning Bridges\n- The 3 Metrics Every PM Should Track Daily',
  count: 10,
  style_samples: 'Professional, insightful, actionable content style',
};

// Variable descriptions for admin UI
export const VARIABLE_DESCRIPTIONS: Record<SupportedVariable, string> = {
  job_title: "User's job title (e.g., 'Entrepreneur', 'Senior Product Manager')",
  existing_topics:
    'Combined list of all topics (chosen + generated history) - for backward compatibility',
  chosen_topics: 'Topics the user has added to their list (left side in step 2) - topics they love',
  generated_topics_history:
    'All topics previously generated by AI during the session (includes added and ignored)',
  count: 'Number of topic suggestions to generate',
  style_samples: "User's writing style samples from step 1",
};

// ============================================================================
// Variable Substitution
// ============================================================================

/**
 * Substitutes dynamic variables in a prompt template with actual values.
 * Supported variables are replaced; unsupported variables remain unchanged.
 */
export function substituteVariables(template: string, variables: Partial<PromptVariables>): string {
  let result = template;

  // Replace each supported variable if it exists in the variables object
  for (const varName of SUPPORTED_VARIABLES) {
    const placeholder = `{{${varName}}}`;
    if (varName in variables) {
      const value = variables[varName as keyof PromptVariables];
      // Convert value to string (handles numbers like count)
      const stringValue = value !== undefined && value !== null ? String(value) : '';
      result = result.split(placeholder).join(stringValue);
    }
  }

  return result;
}

// ============================================================================
// Validation
// ============================================================================

/**
 * Validates a prompt string.
 * Returns validation result with error message if invalid.
 */
export function validatePrompt(prompt: string): ValidationResult {
  if (!prompt || prompt.trim().length === 0) {
    return {
      valid: false,
      error: 'Prompt cannot be empty',
    };
  }

  return { valid: true };
}

/**
 * Validates the entire prompt configuration.
 */
export function validatePromptConfig(config: PromptConfig): ValidationResult {
  const systemValidation = validatePrompt(config.systemPrompt);
  if (!systemValidation.valid) {
    return {
      valid: false,
      error: `System prompt: ${systemValidation.error}`,
    };
  }

  const userValidation = validatePrompt(config.userPrompt);
  if (!userValidation.valid) {
    return {
      valid: false,
      error: `User prompt: ${userValidation.error}`,
    };
  }

  return { valid: true };
}

// ============================================================================
// Database Operations
// ============================================================================

/**
 * Retrieves prompt configuration from the database.
 * Returns default prompts if no custom prompts exist.
 */
export async function getPromptConfig(): Promise<PromptConfig> {
  const supabase = getSupabaseAdmin();

  const { data: configs } = await supabase
    .from('app_config')
    .select('key, value')
    .in('key', [PROMPT_CONFIG_KEYS.SYSTEM_PROMPT, PROMPT_CONFIG_KEYS.USER_PROMPT]);

  const config: PromptConfig = { ...DEFAULT_PROMPT_CONFIG };

  if (configs) {
    for (const item of configs) {
      if (item.key === PROMPT_CONFIG_KEYS.SYSTEM_PROMPT && item.value) {
        config.systemPrompt = item.value;
      } else if (item.key === PROMPT_CONFIG_KEYS.USER_PROMPT && item.value) {
        config.userPrompt = item.value;
      }
    }
  }

  return config;
}

/**
 * Saves prompt configuration to the database.
 * Validates prompts before saving.
 */
export async function savePromptConfig(config: PromptConfig): Promise<void> {
  const validation = validatePromptConfig(config);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  const supabase = getSupabaseAdmin();
  const now = new Date().toISOString();

  // Upsert system prompt
  const { error: systemError } = await supabase.from('app_config').upsert(
    {
      key: PROMPT_CONFIG_KEYS.SYSTEM_PROMPT,
      value: config.systemPrompt,
      description: 'AI system prompt for topic generation',
      updated_at: now,
    },
    { onConflict: 'key' }
  );

  if (systemError) {
    throw new Error('Failed to save system prompt');
  }

  // Upsert user prompt
  const { error: userError } = await supabase.from('app_config').upsert(
    {
      key: PROMPT_CONFIG_KEYS.USER_PROMPT,
      value: config.userPrompt,
      description: 'AI user prompt for topic generation',
      updated_at: now,
    },
    { onConflict: 'key' }
  );

  if (userError) {
    throw new Error('Failed to save user prompt');
  }
}

/**
 * Resets prompt configuration to default values.
 */
export async function resetPromptConfig(): Promise<void> {
  await savePromptConfig(DEFAULT_PROMPT_CONFIG);
}

/**
 * Generates a preview of prompts with sample data substituted.
 */
export function generatePreview(config: PromptConfig): PromptConfig {
  return {
    systemPrompt: substituteVariables(config.systemPrompt, SAMPLE_VARIABLES),
    userPrompt: substituteVariables(config.userPrompt, SAMPLE_VARIABLES),
  };
}
