'use client';

import { useEffect, useState, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { Label } from '@/components/ui/label';
import { Loader2, Save, RotateCcw, Sparkles, Check, Copy, Code } from 'lucide-react';

// Types
interface AIConfig {
  provider: string;
  apiEndpoint: string;
  apiKey?: string;
  apiKeyHeader?: string;
  apiKeyPrefix?: string;
  extraHeaders?: Record<string, string>;
  responsePath?: string;
  apiConfig: Record<string, unknown>;
}

// Default API configurations for each provider
const DEFAULT_OPENAI_CONFIG = {
  provider: 'openai',
  apiEndpoint: 'https://api.openai.com/v1/chat/completions',
  apiKeyHeader: 'Authorization',
  apiKeyPrefix: 'Bearer ',
  responsePath: 'choices[0].message.content',
  apiConfig: {
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: `You're a LinkedIn topic drafter. Your job is to act as a {{job_title}}, look at the topic ideas already drafted and generate 10 more like it that are different enough to be novel.

Each topic should be:
- Specific and actionable
- Written as a compelling LinkedIn post title
- Different from the existing topics but in a similar professional domain
- Formatted like: "Why [Problem/Observation]—And [Solution/Insight]"

Return ONLY a JSON array of topic strings, nothing else.

Core requirement: Always generate 10 unique, professional LinkedIn post topic ideas. If no existing topics are provided, create fresh topics relevant to the job title "{{job_title}}". Output must be a valid JSON array of strings.`,
      },
      {
        role: 'user',
        content: `Here are the existing topic ideas:
{{existing_topics}}

Generate 10 new topic ideas that are different but related to these themes.

Return only a JSON array of 10 topic strings.

IMPORTANT: You MUST generate exactly 10 topic suggestions as a JSON array. The job title is "{{job_title}}" - generate relevant professional topics for this role. Return ONLY a valid JSON array of strings like: ["Topic 1", "Topic 2", ...]. No markdown, no explanation, no code blocks, just the raw JSON array.`,
      },
    ],
    temperature: 0.8,
    max_tokens: 2000,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
  },
};

const DEFAULT_ANTHROPIC_CONFIG = {
  provider: 'anthropic',
  apiEndpoint: 'https://api.anthropic.com/v1/messages',
  apiKeyHeader: 'x-api-key',
  apiKeyPrefix: '',
  extraHeaders: {
    'anthropic-version': '2023-06-01',
  },
  responsePath: 'content[0].text',
  apiConfig: {
    model: 'claude-3-5-sonnet-20241022',
    system: `You're a LinkedIn topic drafter. Your job is to act as a {{job_title}}, look at the topic ideas already drafted and generate 10 more like it that are different enough to be novel.

Each topic should be:
- Specific and actionable
- Written as a compelling LinkedIn post title
- Different from the existing topics but in a similar professional domain
- Formatted like: "Why [Problem/Observation]—And [Solution/Insight]"

Return ONLY a JSON array of topic strings, nothing else.

Core requirement: Always generate 10 unique, professional LinkedIn post topic ideas. If no existing topics are provided, create fresh topics relevant to the job title "{{job_title}}". Output must be a valid JSON array of strings.`,
    messages: [
      {
        role: 'user',
        content: `Here are the existing topic ideas:
{{existing_topics}}

Generate 10 new topic ideas that are different but related to these themes.

Return only a JSON array of 10 topic strings.

IMPORTANT: You MUST generate exactly 10 topic suggestions as a JSON array. The job title is "{{job_title}}" - generate relevant professional topics for this role. Return ONLY a valid JSON array of strings like: ["Topic 1", "Topic 2", ...]. No markdown, no explanation, no code blocks, just the raw JSON array.`,
      },
    ],
    max_tokens: 2000,
    temperature: 0.8,
  },
};

const VARIABLE_DESCRIPTIONS: Record<string, string> = {
  job_title: "User's job title (e.g., 'Entrepreneur', 'Senior Product Manager')",
  existing_topics:
    'Combined list of all topics (chosen + generated history) - for backward compatibility',
  chosen_topics: 'Topics the user has added to their list (left side in step 2) - topics they love',
  generated_topics_history:
    'All topics previously generated by AI during the session (includes added and ignored)',
  style_samples: "User's writing style samples from step 1",
};

const VARIABLES = Object.keys(VARIABLE_DESCRIPTIONS);

export default function AdminPromptsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // Config state - single JSON for entire configuration
  const [jsonConfig, setJsonConfig] = useState<string>(
    JSON.stringify(DEFAULT_OPENAI_CONFIG, null, 2)
  );
  const [jsonError, setJsonError] = useState<string | null>(null);
  // Copy state
  const [copied, setCopied] = useState(false);

  // Fetch current config
  const fetchConfig = useCallback(async () => {
    try {
      const res = await fetch('/api/admin/prompts');
      if (res.ok) {
        const data = await res.json();
        if (data.config) {
          setJsonConfig(JSON.stringify(data.config, null, 2));
        }
      }
    } catch (error) {
      console.error('Error fetching config:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchConfig();
  }, [fetchConfig]);

  // Validate JSON configuration
  const validateConfig = (json: string): { valid: boolean; error?: string; config?: AIConfig } => {
    try {
      const config = JSON.parse(json);

      // Required fields validation
      if (!config.provider || typeof config.provider !== 'string') {
        return { valid: false, error: 'Missing or invalid "provider" field (string required)' };
      }

      if (!config.apiEndpoint || typeof config.apiEndpoint !== 'string') {
        return {
          valid: false,
          error: 'Missing or invalid "apiEndpoint" field (URL string required)',
        };
      }

      if (!config.apiConfig || typeof config.apiConfig !== 'object') {
        return { valid: false, error: 'Missing or invalid "apiConfig" field (object required)' };
      }

      // Validate URL format
      try {
        new URL(config.apiEndpoint);
      } catch {
        return { valid: false, error: 'Invalid "apiEndpoint" URL format' };
      }

      return { valid: true, config };
    } catch (e) {
      return {
        valid: false,
        error: `Invalid JSON: ${e instanceof Error ? e.message : 'Parse error'}`,
      };
    }
  };

  // Save config
  const handleSave = async () => {
    const validation = validateConfig(jsonConfig);
    if (!validation.valid) {
      setJsonError(validation.error || 'Invalid configuration');
      return;
    }

    setSaving(true);
    setMessage(null);
    setJsonError(null);

    try {
      const res = await fetch('/api/admin/prompts', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: jsonConfig, // Send the entire config object
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Failed to save configuration');
      }

      setMessage({ type: 'success', text: 'Configuration saved successfully' });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to save configuration';
      setMessage({ type: 'error', text: errorMessage });
    } finally {
      setSaving(false);
    }
  };

  // Reset to defaults
  const handleReset = () => {
    setJsonConfig(JSON.stringify(DEFAULT_OPENAI_CONFIG, null, 2));
    setJsonError(null);
    setMessage({ type: 'success', text: 'Reset to default OpenAI configuration' });
  };

  // Copy to clipboard
  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(jsonConfig);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Insert variable at cursor
  const insertVariable = (variable: string) => {
    const placeholder = `{{${variable}}}`;
    navigator.clipboard.writeText(placeholder);
    setMessage({ type: 'success', text: `Copied ${placeholder} to clipboard` });
    setTimeout(() => setMessage(null), 2000);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-100">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">AI Prompts Configuration</h1>
        <p className="text-muted-foreground">
          Configure the AI API request for idea generation (Step 2 &amp; Edit Settings)
        </p>
      </div>

      {message && (
        <div
          className={`p-4 rounded-lg border ${
            message.type === 'success'
              ? 'bg-green-500/10 border-green-500/30 text-green-600'
              : 'bg-destructive/10 border-destructive/30 text-destructive'
          }`}
        >
          {message.text}
        </div>
      )}

      {/* Dynamic Variables */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Dynamic Variables
          </CardTitle>
          <CardDescription>
            Use these placeholders in your prompts. They will be replaced at runtime. Click to copy.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-3 sm:grid-cols-2">
            {VARIABLES.map(variable => (
              <div
                key={variable}
                className="flex items-start gap-3 p-3 rounded-lg border bg-muted/50 cursor-pointer hover:bg-muted/70 transition-colors"
                onClick={() => insertVariable(variable)}
                title="Click to copy placeholder"
              >
                <Badge variant="secondary" className="font-mono text-xs shrink-0">
                  {`{{${variable}}}`}
                </Badge>
                <span className="text-sm text-muted-foreground">
                  {VARIABLE_DESCRIPTIONS[variable]}
                </span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Provider Selection & JSON Editor */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Code className="h-5 w-5 text-primary" />
            API Configuration
          </CardTitle>
          <CardDescription>
            Configure any LLM provider with full JSON configuration. Include API endpoint, headers,
            API key, and request body.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* JSON Error */}
          {jsonError && (
            <div className="p-3 rounded-lg border bg-destructive/10 border-destructive/30 text-destructive text-sm">
              {jsonError}
            </div>
          )}

          {/* JSON Editor */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="jsonConfig">Full Configuration (JSON)</Label>
              <Button variant="ghost" size="sm" onClick={copyToClipboard} className="h-8 gap-1">
                {copied ? (
                  <>
                    <Check className="h-4 w-4 text-green-500" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="h-4 w-4" />
                    Copy
                  </>
                )}
              </Button>
            </div>
            <Textarea
              id="jsonConfig"
              value={jsonConfig}
              onChange={e => {
                setJsonConfig(e.target.value);
                setJsonError(null);
              }}
              rows={30}
              className="font-mono text-sm"
              placeholder="Enter full API configuration JSON..."
            />
          </div>

          {/* Actions */}
          <div className="flex justify-between pt-4">
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="outline" disabled={saving} className="gap-2">
                  <RotateCcw className="h-4 w-4" />
                  Reset to Defaults
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Reset to Default Configuration?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This will restore the JSON configuration to the default OpenAI configuration.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handleReset}>Reset</AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>

            <Button onClick={handleSave} disabled={saving} className="gap-2">
              {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              Save Configuration
            </Button>
          </div>

          {/* Help Text */}
          <div className="text-xs text-muted-foreground space-y-2 pt-4 border-t">
            <p className="font-medium">Required Fields:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>
                <code className="bg-muted px-1 rounded">provider</code> - Provider name (e.g.,
                &quot;openai&quot;, &quot;anthropic&quot;, &quot;groq&quot;, &quot;mistral&quot;)
              </li>
              <li>
                <code className="bg-muted px-1 rounded">apiEndpoint</code> - Full API URL
              </li>
              <li>
                <code className="bg-muted px-1 rounded">apiConfig</code> - Request body object
              </li>
            </ul>
            <p className="font-medium mt-3">Optional Fields:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>
                <code className="bg-muted px-1 rounded">apiKey</code> - API key (or use environment
                variable)
              </li>
              <li>
                <code className="bg-muted px-1 rounded">apiKeyHeader</code> - Header name (default:
                &quot;Authorization&quot;)
              </li>
              <li>
                <code className="bg-muted px-1 rounded">apiKeyPrefix</code> - Key prefix (default:
                &quot;Bearer &quot;)
              </li>
              <li>
                <code className="bg-muted px-1 rounded">extraHeaders</code> - Additional headers
                object
              </li>
              <li>
                <code className="bg-muted px-1 rounded">responsePath</code> - JSON path to extract
                content (e.g., &quot;choices[0].message.content&quot;)
              </li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
